id: P12A1F419
initial_creation_type: ocr
source_metadata:
  volumes:
    9fcd782415404756a23c52f5076c21cb:
      base_file: v057.txt
      image_group_id: I1PD95902
      title: བསྟན་བཅོས་བཞི་བརྒྱ་པ་ཞེས་བྱ་བའི་ཚིག་ལེའུར་བྱས་པ།
      total_pages: 1605
      volume_number: 57
